Repository MCPJam/inspector, pull requests merged in 2025-09, with the labels that each got.

#583 Use zod v3 everywhere but ollama
  .github/workflows/lint.yml
  package-lock.json
  package.json
  server/package.json
  server/routes/mcp/chat.ts
  server/routes/mcp/export.ts
  server/routes/mcp/tools.ts
  server/services/mcp-http-bridge.ts
  server/tsup.config.ts
  shared/tools.ts
Labels: size:S

#585 Added dev dependencies and updated env.local
  .env.local
  package-lock.json
  package.json
Labels: Easy, size:XS, lgtm

#590 modify posthog analytics
  .env.local
  .env.production
  client/src/App.tsx
  client/src/components/ActiveServerSelector.tsx
  client/src/components/ChatTab.tsx
  client/src/components/ServersTab.tsx
  client/src/components/auth/auth-upper-area.tsx
  client/src/components/connection/JsonImportModal.tsx
  client/src/components/setting/AccountApiKeySection.tsx
  client/src/components/setting/ProviderConfigDialog.tsx
  client/src/components/tools/ParametersPanel.tsx
  client/src/logs/PosthogUtils.ts
Labels: enhancement, size:L
