Repository MCPJam/inspector, pull requests merged in 2025-10, with the labels that each got.

#596 Accept other mcpconfig types
  evals-cli/src/evals/index.ts
  evals-cli/src/utils/config-transformer.ts
Labels: enhancement, size:L

#597 Create evals from UI
  client/src/components/EvalsTab.tsx
  client/src/components/chat/model-selector.tsx
  client/src/components/evals/SuiteRow.tsx
  client/src/components/evals/eval-runner.tsx
  client/src/components/evals/helpers.ts
  client/src/components/evals/iteration-card.tsx
  client/src/components/evals/iteration-details.tsx
  client/src/components/evals/types.ts
  evals-cli/dist/index.js
  evals-cli/dist/index.js.map
  evals-cli/src/db/tests.ts
  evals-cli/src/evals/index.ts
  evals-cli/src/evals/runner.ts
  server/routes/mcp/evals.ts
  server/routes/mcp/index.ts
  server/utils/eval-transformer.ts
Labels: enhancement, size:XL

#600 remove import
  server/routes/mcp/index.ts
Labels: size:XS

#604 Add GPT OSS
  client/src/components/ChatTab.tsx
  client/src/components/chat/model-selector.tsx
  client/src/components/evals/eval-runner.tsx
  client/src/hooks/use-chat.ts
  evals-cli/src/evals/runner.ts
  server/routes/mcp/chat.ts
  server/routes/mcp/evals.ts
  server/services/eval-agent.ts
  server/utils/eval-transformer.ts
  shared/backend-conversation.ts
  shared/types.ts
Labels: size:L

#607 Polish types
  client/src/components/chat/model-selector.tsx
  evals-cli/src/evals/runner.ts
  package.json
Labels: enhancement, size:L

#612 Add Apps Sdk Testing Support
  client/src/components/ChatTab.tsx
  client/src/components/ToolsTab.tsx
  client/src/components/chat/message.tsx
  client/src/components/chat/openai-component-renderer.tsx
  client/src/components/chat/tool-call.tsx
  client/src/components/connection/server-card-utils.ts
  client/src/components/tools/ResultsPanel.tsx
  client/src/lib/chat-types.ts
  client/src/lib/openai-apps-sdk-utils.ts
  server/routes/mcp/chat.ts
  server/routes/mcp/resources.ts
  server/routes/mcp/tools.ts
  server/services/mcpjam-client-manager.ts
  shared/backend-conversation.ts
  shared/http-tool-calls.ts
  shared/sse.ts
Labels: enhancement, size:XXL
